baseURL: https://blog.djm.me/
languageCode: en-GB
theme: hugo-tania
title: Dave James Miller's Blog

params:
  author: Dave James Miller
  mainSections:
    - posts
  titleEmoji: 'ğŸ‘¨ğŸ»â€ğŸ’»'

menu:
  header:
    - weight: 1
      name: Home
      url: /
    - weight: 2
      name: Tags
      url: /tags/
  footer:
    - weight: 1
      name: RSS Feed
      url: /index.xml
    - weight: 2
      name: Powered by Hugo
      url: https://gohugo.io/
    - weight: 3
      name: Tania Theme
      url: https://github.com/WingLim/hugo-tania
    - weight: 4
      name: GitHub
      url: https://github.com/d13r/blog
